### ISSUE TITLE
The charm should use the default snap track instead of going for `latest/stable`

### ISSUE THREAD

**Issue by simondeziel** [canonical/charm-lxd#123]

**Comment by simondeziel** [comment]
@tomponline with LXD not being seeded by default going forward, what do you think of changing the behaviour of the charm to:

* change the snap-channel config to default to `auto`
* when `auto` is used: check if `lxd-installer` is present and use it to pick the right track/channel
* when `auto` is used: if no `lxd-installer` install from the current LTS (`5.21/stable`)

**Comment by tomponline** [comment]
@simondeziel 

> change the snap-channel config to default to auto
Sounds good.

> when auto is used: check if lxd-installer is present and use it to pick the right track/channel
Sounds good.

> when auto is used: if no lxd-installer install from the current LTS (5.21/stable)
Lets not add more version logic into other components except lxd-installer and snap store. 
The default track will be changing soon to 5.21, so the end result will be the same here without needing to code it into the charm.
