### ISSUE TITLE
Make use of the operator library for package management

### ISSUE THREAD

**Issue by stgraber** [canonical/charm-lxd#24]
https://github.com/canonical/operator-libs-linux has been published now and we should be able to use it for snap package management. Apparently it gets pulled through fetch-lib with charmcraft.

**Comment by simondeziel** [comment]
The v2 snap library (https://charmhub.io/operator-libs-linux/libraries/snap) ticks all the boxes (cohort, alias, dangerous/local install, config set, etc) so we should make use of it.

**Comment by simondeziel** [comment]
The new plan in #123 is to piggy back on `lxd-installer` to pick the right channel when available. `lxd-installer` should be available everywhere on Noble so let's not add the ops libs for snap management for the rare case it would be needed.
