### ISSUE TITLE
Charm fails to build on foreign architectures

### ISSUE THREAD

**Issue by stgraber** [canonical/charm-lxd#78]
https://launchpadlibrarian.net/599796272/buildlog_charm_ubuntu_focal_armhf_charm-lxd-edge_BUILDING.txt.gz
https://launchpadlibrarian.net/599770402/buildlog_charm_ubuntu_focal_s390x_charm-lxd-edge_BUILDING.txt.gz
https://launchpadlibrarian.net/599770325/buildlog_charm_ubuntu_focal_ppc64el_charm-lxd-edge_BUILDING.txt.gz

**Comment by simondeziel** [comment]
Most likely due to https://github.com/canonical/charm-lxd/commit/42f28a38a5f43102a5b0204262d673c0c9987fc1
I'll see if there is a way to use the compiled binary only on amd64
